#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
USE_PROCD=1

START=99


start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/ddns-rs run -c /etc/ddns-rs/ddns.conf
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}